services:
    balancer:
        image: "nginx:latest"
        volumes:
            - "./architectures.conf:/etc/nginx/nginx.conf:ro"
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - api
        networks:
            - "app-network"
        deploy:
            resources:
                limits:
                    cpus: "2"
                    memory: "2GB"

    api:
        image: architectures/noclean
        build:
            dockerfile: "noarch.dockerfile"
        expose:
            - "80"
        networks:
            - "app-network"
        depends_on:
            - "database"
        environment:
            ConnectionString: "Server=database;Port=5432;Database=architectures;User Id=postgres;Password=docker1234@;"
        deploy:
            mode: replicated
            replicas: 2
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 2
            resources:
                limits:
                    cpus: "2"
                    memory: "1.5GB"

    database:
        image: "postgres:latest"
        command: postgres -c 'max_connections=450'
        networks:
            - "app-network"
        environment:
            POSTGRES_PASSWORD: docker1234@
        expose:
            - "5432"
        deploy:
            resources:
                limits:
                    cpus: "4"
                    memory: "3GB"

networks:
    app-network: {}